[build]
  command = "cd frontend/Day06/react-router-app && pnpm install --no-frozen-lockfile && pnpm build"
  publish = "frontend/Day06/react-router-app/dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

