[build]
  base = "frontend/Day06/react-router-app"
  command = "cd frontend/Day06/react-router-app && pnpm install && pnpm build"
  publish = "frontend/Day06/react-router-app/dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

